CURRENT_USER=$(whoami)
sudo -u postgres psql << EOF
CREATE ROLE $CURRENT_USER WITH LOGIN PASSWORD 'password';
ALTER USER $CURRENT_USER PASSWORD 'password';
ALTER ROLE $CURRENT_USER CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE postgres TO $CURRENT_USER;
GRANT ALL ON SCHEMA public TO $CURRENT_USER;
GRANT ALL ON ALL TABLES IN SCHEMA public TO $CURRENT_USER;
EOF

psql -U $CURRENT_USER -d postgres -a -f init.sql