runtime: nodejs18
service: saad-mufti
env: standard

instance_class: F1

env_variables:
  NODE_ENV: 'production'

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2

handlers:
- url: /static
  static_dir: build/static

- url: /(.*\.(json|ico|js|html))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js|html)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html
